# Generated by Django 4.2.5 on 2023-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='note_type',
            field=models.IntegerField(choices=[(0, '/w')], default=0, verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='role',
            field=models.IntegerField(choices=[(0, 'Клиент'), (1, 'Сотрудник')], default=0, verbose_name='Роль'),
        ),
    ]
