# Generated by Django 4.2.5 on 2023-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0002_notemodel_note_type_alter_personmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='text',
            field=models.TextField(verbose_name='Текст записи'),
        ),
    ]
