# Generated by Django 4.2.5 on 2023-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0003_alter_notemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='Имя внесшего запись'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
