# Generated by Django 4.2.5 on 2023-09-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0005_alter_personmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(default='', max_length=50, verbose_name='Имя клиента')),
                ('station_name', models.CharField(max_length=4, verbose_name='Название станции')),
                ('file_name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('file_date', models.DateField(verbose_name='Дата файла')),
                ('file_time', models.TimeField(verbose_name='Время файла')),
                ('note_date', models.DateField(auto_now=True, verbose_name='Дата запроса')),
                ('note_time', models.TimeField(auto_now=True, verbose_name='Время запроса')),
            ],
            options={
                'verbose_name_plural': 'Запросы станций',
            },
        ),
    ]
