# Generated by Django 4.2.5 on 2023-09-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0006_filedownloadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedownloadmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='filedownloadmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dot_bank.personmodel', verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
