# Generated by Django 4.2.5 on 2023-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0005_alter_notemodel_note_type'),
        ('dot_bank', '0007_remove_filedownloadmodel_username_and_more'),
    ]

    operations = [
    ]
