# Generated by Django 4.2.5 on 2024-05-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0008_personmodel_bot_number_alter_notemodel_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstuctionsDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('note_date', models.DateField(auto_now=True, verbose_name='Дата запроса')),
                ('note_time', models.TimeField(auto_now=True, verbose_name='Время запроса')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dot_bank.personmodel', verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name_plural': 'Запросы инструкций',
            },
        ),
    ]
