# Generated by Django 4.2.5 on 2024-05-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0009_instuctionsdownloadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='bot_number',
            field=models.IntegerField(choices=[(2, 'UciDataBot'), (3, 'GD_supBot')], default=2, verbose_name='Имя бота'),
        ),
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст отзыва')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('bot_number', models.IntegerField(choices=[(2, 'UciDataBot'), (3, 'GD_supBot')], default=2, verbose_name='Имя бота')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dot_bank.personmodel', verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
