# Generated by Django 4.2.5 on 2024-05-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0008_merge_20230926_2018'),
        ('dot_bank', '0010_alter_personmodel_bot_number_feedbackmodel'),
    ]

    operations = [
    ]
