# Generated by Django 4.2.5 on 2024-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0011_merge_20240505_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInstructionModel',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'Клиент'), (1, 'Сотрудник')], default=0, verbose_name='Роль')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('authentication', models.BooleanField(default=True, verbose_name='Подтверждение')),
                ('bot_number', models.IntegerField(choices=[(2, 'UciDataBot'), (3, 'GD_supBot')], default=2, verbose_name='Имя бота')),
            ],
        ),
    ]
