# Generated by Django 4.2.5 on 2024-05-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_bank', '0012_personinstructionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personinstructionmodel',
            options={'verbose_name_plural': 'Люди запрашивающие инструкции'},
        ),
        migrations.RemoveField(
            model_name='personinstructionmodel',
            name='authentication',
        ),
        migrations.RemoveField(
            model_name='personinstructionmodel',
            name='bot_number',
        ),
        migrations.RemoveField(
            model_name='personinstructionmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personinstructionmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personinstructionmodel',
            name='role',
        ),
        migrations.AddField(
            model_name='personinstructionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personinstructionmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dot_bank.personmodel', verbose_name='Имя пользователя'),
        ),
    ]
